package broker;

public enum ErrorCode {
    FEASIBLE,
    FEASIBLE_ZERO,
    INFEASIBLE_Y,
    INFEASIBLE_Z,
    INFEASIBLE_X,
    INFEASIBLE_XY,
    INFEASIBLE_S,
    INFEASIBLE_T,
    INFEASIBLE_OBJ,
    DIFFERENT_RENT,
}
